### ISSUE TITLE
Custom Field - File Upload - Enable Multi-File Upload

### ISSUE THREAD

**Issue by martin-williams** [jupitercow/gravity-forms-post-updates#3]
I need to allow users to upload images and am trying to use the custom field - file upload. Uploads are successful when I do not enable multi-file uploads. However, I need to allow multiple files to be uploaded since these images will be part of a gallery.

**Comment by jupitercow** [comment]
This isn't currently supported. I would like to get it working, but it is going to take a little time unfortunately for me to get to it. My estimate is 2 weeks, but I am not guaranteeing anything right now.

**Comment by ingageco** [comment]
@jupitercow thanks for the info - can you give us some insight into why it's not supported so maybe we can contribute to the solution?

**Comment by jupitercow** [comment]
It was added more recently, and I just need to review how it works. The
file upload support was one of the more complex things I had to add, so I
need some time to review how it works and modify functionality to work with
it. It might not be super complex to adapt the existing single file upload
functionality, but I am not totally sure what to expect yet. I have had
some personal issues over the past month or so that are slowing me down on
this, but I should be back up in a more caught up state over the next
couple weeks.

If somebody can work on the issue, I am happy to get entertain any pull
requests and get them into the repo.

**Comment by kmgilbert100** [comment]
@jupitercow Any updates on this?

**Comment by ingageco** [comment]
Hey @jupitercow - any update on this item and if you'll be able to fix it soon? Thanks for your time.

**Comment by jupitercow** [comment]
Yes. This will be ready by Monday in the next update.

**Comment by jupitercow** [comment]
Can you guys test the latest version. It is working for me now, and I want to see if there are still issues for anyone else. If you have issues, can post some details. I really want to make sure this working as soon as possible.

Thanks.
